---
title: "Class 5: Motivation and Policy Background"
date: 2026-01-27
---

## Relevant links and other materials

Links to papers are listed alongside the full reference. PDFs of each paper are also available on **Canvas**.

- <i class="fas fa-book"></i> Required readings for this module:
    - Chapter 5 of [Causal Inference: The Mixtape](https://mixtape.scunning.com/)
    - Chapter 14 of [The Effect: An Introduction to Research Design and Causality](https://theeffectbook.net/)
- <i class="fas fa-external-link-square-alt"></i> Supplemental information and readings:
    - Chapters 1-2, and 4 of [Causal Inference: The Mixtape](https://mixtape.scunning.com/)
    - Chapters 1-5, 10, and 13 of [The Effect: An Introduction to Research Design and Causality](https://theeffectbook.net/)
    - Chapters 2-3 of [@angrist2009]
- <i class="fa fa-database"></i> Data for this module:
    - [Medicare Advantage](https://github.com/imccart/Medicare-Advantage) repository

## Objectives

- Explain some of the history and institutional details of Medicare Advantage 
- Understand the economic theory underlying competition and pricing
- Understand, explain, and be able to calculate common measures of competition
