---
title: "Class 23: Medicaid Expansion and Hospital Uncompensated Care"
date: 2026-04-07
---

The goal of this module is to understand difference-in-differences as a causal identification strategy. We'll do this in the context of Medicaid expansion and its effect on hospital uncompensated care.

## Readings and other links

Links to papers are listed alongside the full reference

- <i class="fas fa-book"></i> Required readings for this module:
    - Chapters 8-9 of [Causal Inference: The Mixtape](https://mixtape.scunning.com/)
    - Chapters 16-18 of [The Effect: An Introduction to Research Design and Causality](https://theeffectbook.net/)
- <i class="fas fa-external-link-square-alt"></i> Supplemental information and readings:
    - Chapter 5 of [@angrist2009]
    - [@courtemanche2017]
    - [@obama2016]
- <i class="fa fa-database"></i> Data for this module:
    - [Hospital Cost Report Information System (HCRIS)](https://github.com/imccart/HCRIS) repository


## Objectives

- Understand some of the large changes introduced by the Affordable Care Act
- Explain what we mean by "Medicaid expansion"
- Understand HCRIS data on hospital uncompensated care

## Activities

- Summarize trends in uncompensated care over time
- Compare uncompensated care in Medicaid expansion vs. non-expansion states
