---
title: "Resources"
toc: false
format:
  html:
    page-layout: full
---

## Git and GitHub with Open OnDemand

To successfully push/pull from GitHub in Open OnDemand (or any local computer really), you'll need to first get an ssh key and add it to your GitHub settings. To do this, open a new terminal in Open OnDemand, and do the following

1. `ls -al ~/.ssh`. This will view a list of files in the .ssh directory, and from there you can confirm that an `id_rsa.pub` file exists (this is a pulic key already created for you).
2. `cat ~/.ssh/id_rsa.pub`. This will show you the key, from which you can copy it (in its entirety) and paste it as a new .ssh key in GitHub.

Once you have you're .ssh key, you're ready to initiate and sync a git repo. I've found the easiest way to do this is to first create a blank repository in GitHub (no ReadMe, no .gitignore...just completely empty). Then, in Open OnDemand, again navigate to the terminal, navigate to the correct directory that you want to place under version control, and follow these steps:

1. `git init`
2. `git config --global user.email "your email"`. You must use the same email that you used to register GitHub (which should also be your Emory email address in order to get all the right features).
3. `git config --global user.name "your name"`. This can be anything...it's what will show up as the user name as you view the version history.
4. Create a ReadMe.txt file in your directory.
5. `git commit -m "first commit"`. Your first commit
6. `git branch -M main`. This puts you on the main branch of your repository.
7. `git remote add origin "git url"`. This will sync your local git with GitHub online.
8. `git push -u origin main`. This pushes your changes to GitHub.

## General Resources

Here are a few additional resources that you may find helpful throughout the semester. I'll add to these as we go.

- Some resources for honing your data analysis skills in `R`:
  - [R for Data Science](https://r4ds.had.co.nz/) by Hadley Wickham and Garrett Grolemund. This is the go-to resource for starting to work with `R`. Highly recommended, free, and informative.
  - [R Language Basics](https://raw.githack.com/uo-ec607/lectures/master/04-rlang/04-rlang.html#1) by Grant McDermott
  - [Data cleaning and wrangling in R](https://raw.githack.com/uo-ec607/lectures/master/05-tidyverse/05-tidyverse.html#1) by Grant McDermott
- Some free econometric resources
  - [Causal Inference Book](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/) by Jamie Robin and Miguel Hernan
  - [Econometrics](https://www.ssc.wisc.edu/~bhansen/econometrics/) by Bruce Hansen
  - [Introductory Econometrics](https://github.com/NickCH-K/econometrics) class notes from Nick Huntington-Klein
  - [Econometrics Notes](http://www.carolinacaetano.net/) from Carolina Caetano at UGA
  - Ever wish you had a central resource for lots of little commands and how to do things in different stats packages? Nick Huntington-Klein thought the same thing in his [Library of Statistical Techniques (LOST)](https://lost-stats.github.io/).

