---
title: "Homework 5"
format:
  html: default
  pdf: default
---

## Instructions
In this assignment, you'll work with hospital cost report data and Medicaid expansion information to study the effect of Medicaid expansion on hospital uncompensated care. You'll need the [HCRIS GitHub Repo](https://github.com/imccart/HCRIS) for the hospital data (which you've already used in homework 4), along with Medicaid expansion dates by state from the [Kaiser Family Foundation](https://www.kff.org/). Some background code for working with the KFF expansion data is available in the [Insurance Access repository](https://github.com/imccart-test/insurance-access), but all you really need is the single KFF CSV file. As we discussed in class, you'll need to merge the HCRIS and KFF data using a state crosswalk.

The due date for initial submission is **4/23**, the revision due date is **4/28**, and the final due date is the date of our final exam, **5/5**.

## Summarize the data

1. Provide a table of mean hospital uncompensated care (in millions of dollars) by year, from 2010 through 2018. How has uncompensated care changed over time?

2. Plot mean uncompensated care over time separately for states that expanded Medicaid in 2014 versus states that never expanded. Drop all states that expanded after 2014. Does the graph suggest a potential treatment effect?

3. Using 2012 and 2015 as your pre and post periods, present a 2x2 DD table of mean uncompensated care for expansion versus non-expansion states (again focusing only on 2014 expanders and never-expanders).

4. Briefly discuss what policies or events might explain the trends you observe. Why might we expect Medicaid expansion to affect uncompensated care?


## Estimate ATEs
For the rest of the assignment, we're going to apply the difference-in-differences estimator to the question of Medicaid expansion and hospital uncompensated care.

5. Estimate the effect of Medicaid expansion on hospital uncompensated care using a standard DD regression estimator, focusing only on states that expanded in 2014 versus those that never expanded.

6. Include hospital and year fixed effects in your estimates using the `fixest` package. Cluster your standard errors at the state level. How do your results compare to those in question 5?

7. Repeat the analysis in question 6 but include all states (even those that expanded after 2014). Are your results different? If so, why?

8. Provide an "event study" graph showing the effects of Medicaid expansion in each year. Use the specification that includes hospital and year fixed effects, limited to states that expanded in 2014 or never expanded (with 2013 as the reference year).

9. Repeat part 8 but include all states that expanded after 2014. You will need to construct an "event time" variable and bin end points as discussed in class.

10. Summarize your findings from questions 5-9. What is the effect of Medicaid expansion on hospital uncompensated care? Do the event study graphs suggest any concerns about the parallel trends assumption? Briefly discuss one limitation of the standard TWFE estimator in the context of staggered Medicaid expansion.
